services:

  express:
    container_name: laptop_express
    build:
      context: .
    env_file:
      - ./dotenv_files/.env
    ports:
      - "3000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    container_name: laptop_redis
    image: redis:7-alpine
    env_file:
      - ./dotenv_files/.env
    volumes:
      - ./data/redis/data:/data
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3001:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
  
  